// examples/react-spa/App.tsx
import { AuthProvider, useAuth } from "@oauth-spa-kit/react";

function Profile() {
  const { ready, loggedIn, user, login, logout } = useAuth();

  if (!ready) return <p>Loading...</p>;
  if (!loggedIn) return <button onClick={() => login()}>Log in</button>;

  return (
    <div>
      <p>Signed in as {String(user?.sub)}</p>
      <button onClick={() => logout()}>Log out</button>
    </div>
  );
}

export default function App() {
  return (
    <AuthProvider>
      <Profile />
    </AuthProvider>
  );
}

// examples/nuxt-app/app.vue
<script setup lang="ts">
const { ready, loggedIn, user, login, logout } = useAuth()
</script>

<template>
  <p v-if="!ready">Loading...</p>
  <button v-else-if="!loggedIn" @click="login()">Log in</button>
  <div v-else>
    <p>Signed in as {{ user?.sub }}</p>
    <button @click="logout()">Log out</button>
  </div>
</template>
